### ISSUE TITLE
Street Fighter colllection USA disk 1

### ISSUE THREAD

**Issue by Biz555** [williamdsw/saroo-configuration-list#5]
Hello. When I play this game about 20% of the left hand screen is missing and a little of the right. Any idea of a code to fix?

Thanks
![20241001_152704](https://github.com/user-attachments/assets/3d39a639-ee11-44d6-978a-0619514fa39c)

**Comment by williamdsw** [comment]
The same thing happens on emulators:

SAROO:
![Screenshot 2024-10-03 22-11-38](https://github.com/user-attachments/assets/9682ee02-254e-4e0c-92ac-5a2ba285ae69)

Yabause:
![Screenshot_1](https://github.com/user-attachments/assets/a19f98a0-3e0d-4ef7-b975-d285e163bc6e)

SSF:
![Screenshot_5](https://github.com/user-attachments/assets/a490dd87-c9b1-4c68-bfb3-bf9f21f33ef2)

Also check this footage:
https://youtu.be/o9sTPbK3ay4

**Comment by Biz555** [comment]
thanks for replying. Is not something that can be fixed thru the config file?

**Comment by williamdsw** [comment]
> thanks for replying. Is not something that can be fixed thru the config file?

I think it's a game issue, since it does happen on other cenarios (emulators, maybe other ODEs).
But I maybe be possible to change in-game this background by hacking it's memory address.
For this you will need to ask the devs on how to do it.

**Comment by Biz555** [comment]
thanks buddy. Any specific devs i can ask?

**Comment by williamdsw** [comment]
Open an issue here:
https://github.com/tpunix/SAROO

**Comment by Biz555** [comment]
Thanks Buddy. I just open the issue now.

Also all regions of resident evil run with strange frame rate in the saroo. Got any fix?

Alex
